### ISSUE TITLE
Create a score-board of environment stats

### ISSUE THREAD

**Issue by DimitrisVou** [c7-project/ants#29]
We need to display the things we have on screen like the number of holes,ants(Underground and Above)
total sugar(and eaten),number of rocks

**Comment by jmsv** [comment]
Things that need doing for this issue:

- Window width needs to be expanded past 900 to accommodate the score board, maybe to 1050 or something
- A background image should be put in the gap with the value titles embedded in the image, so they don't have to be rendered in every frame. The titles should have uniform spacing to make adding values easier
- Values need to be added over the image under their respective titles

Also, as there will probably be space left over at the bottom of the scoreboard image, we could display keyboard commands for reference, e.g. 'A: Add Ant, R: Add Rock'

**Comment by jmsv** [comment]
Values listed:

- FPS
- Ants on ground
- Ants underground
- Number of holes
- Active sugar
- Sugar eaten
- Number of rocks
