### ISSUE TITLE
Rocks should only be added when not touching other rocks

### ISSUE THREAD

**Issue by jmsv** [c7-project/ants#34]
It causes some problems with ants' collisions, and it looks unrealistic so the `Hole` class' `__init__` should raise an exception when a collision is detected. This exception should then be handled where appropriate

**Comment by DimitrisVou** [comment]
Jan said he will have it done by tommorow

**Comment by diow** [comment]
yeah, thanks for that :D

**Comment by jmsv** [comment]
Close the issue when you've committed a working solution
