### ISSUE TITLE
Create food

### ISSUE THREAD

**Issue by jmsv** [c7-project/ants#5]
A bit of research should be done into what ants eat that we could use in the program.

Graphics need to be made, and the food needs to be implemented in terms of how the ants move.

**Comment by AntonioRoldan** [comment]
![76538cdd30b03c874ec126e6f9795e11](https://cloud.githubusercontent.com/assets/22200326/20069113/2ba5fa0c-a513-11e6-9829-ffa551e7d17a.jpg)
![banana-024](https://cloud.githubusercontent.com/assets/22200326/20069112/2ba597b0-a513-11e6-910e-37c5c603531a.jpg)
![graperedseedless](https://cloud.githubusercontent.com/assets/22200326/20069114/2ba85306-a513-11e6-9f4f-63c06e48f851.png)
![green-apple_1](https://cloud.githubusercontent.com/assets/22200326/20069116/2bab0754-a513-11e6-800f-9acf81a4e6e5.jpg)
![unnamed](https://cloud.githubusercontent.com/assets/22200326/20069117/2bab36a2-a513-11e6-9b1a-5fafaa2d5c6f.png)

**Comment by AntonioRoldan** [comment]
How about we use Bieber's face as a poisonous obstacle?

**Comment by JanSargsyan** [comment]
I will do it, I mean food

**Comment by jmsv** [comment]
@diow Can you commit?
