### ISSUE TITLE
Ants need movement variants

### ISSUE THREAD

**Issue by jmsv** [c7-project/ants#6]
Vari-**ants** - get it?

4 images (21*21px) need to be created of different frames of the ant walking. The `move` function can iterate through the images, and the `stop` method can select the 'stationary' image.

**Comment by JanSargsyan** [comment]
I will do it, animation of moving ant

**Comment by JanSargsyan** [comment]
I promise to commit it today :)

**Comment by jmsv** [comment]
I've put some information in a comment in 97261332c4e03da22f91e5ab130eba3ec8fd1e54
