### ISSUE TITLE
Videos to track development

### ISSUE THREAD

**Issue by jmsv** [c7-project/ants#8]
We need to take screen captures of the program throughout development

**Comment by jmsv** [comment]
I have a better idea then using screen capture software! The program could have a Boolean value '`video_mode`'. The program could record it's frames without the need for third party software, meaning that the frame rate will be perfectly maintained - this is how to do save a frame:

```
pygame.image.save(screen, "image-name.jpeg")
```

The image name can be implemented in Python as: `"ants-{}-frame-{}".format(date, frame_number)`, where `date` and `frame_number` are variable.

As `pygame.image.save` has to save an image in every iteration of the main game loop, the real FPS will drop very low. This is irrelevant however, because when the video is made from the saved frames, a 30FPS video can be made. The 'fps' count in the top-right can be set constantly to 'fps:30' when `video_mode` is True.

I can do the programming for this - to make the video, the images just need to be used as video frames, each 1/30 seconds.

**Comment by jmsv** [comment]
The commit that just referenced this issue has implemented the frame capture. To enable it, go to `ants/classes/video.py` and change the value of `video_mode` to `True`

**Comment by jmsv** [comment]
Once we've finished the programming I'll make a 'finished version' video thing

**Comment by MogomotsiSaya** [comment]
Didn't release until after i commit i had to put the hashtag

**Comment by MogomotsiSaya** [comment]
Didnt realise until the update code commit i had to use the hashtag

**Comment by jmsv** [comment]
An up-to-date video of the program has been made: <https://youtu.be/m7c78RZ0-nY>

**Comment by MogomotsiSaya** [comment]
Cheers mate
