### ISSUE TITLE
Generate obstacles avoided by ants

### ISSUE THREAD

**Issue by jmsv** [c7-project/ants#9]
Top view of rocks etc.

**Comment by JanSargsyan** [comment]
The same, I will carry everything connected to graphics. Rocks or obstacles as well.

**Comment by jmsv** [comment]
Jan made the top-view rock sprites, Elliot committed most of the solution at 0ccf04fb21cc75a6331b2e3ab3b0443aaeef5789 then I improved the collision accuracy and fixed a few bugs in commit 2078bcd530b59b2ba3283616aec0e764109d8539
